# Generated by Django 4.0 on 2023-08-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_icon_photo'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая стоимость')),
                ('session', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ключ сессии')),
                ('flag_paid', models.CharField(choices=[('y', 'оплачен'), ('ex', 'ожидает оплаты'), ('n', 'неоплачен')], default='n', max_length=2, verbose_name='статус оплаты')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='accounts.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
